name: Deploy to EC2 Instance

on: 
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print my name
        run: |
            echo "Sunil Gaddi"
            echo "Devops Engineer"
      - name: Current folder
        run: |
            pwd
